;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Data.GroggyDamage",DevComment="무기의 Groggy 증가량 전달")
+GameplayTagList=(Tag="Data.MaxGroggy",DevComment="초기 최대 Groggy 전달")
+GameplayTagList=(Tag="Data.StunDuration",DevComment="스턴 지속시간 전달")
+GameplayTagList=(Tag="State.Stunned",DevComment="현재스턴 상태")

